/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mainproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import utilities.UserSession;

/**
 *
 * @author Hiteshi Joshi
 */
public class managetask extends javax.swing.JFrame {
    ArrayList<Integer> idsList = new ArrayList<Integer>();
  int selectedId=-1;
  String selectedTaskStatus;

    /**
     * Creates new form managetask
     */
    public managetask() {
        initComponents();
        fetchtaskslist();
    }
    public managetask(String taskStatus) {
    initComponents();
    lbTitle.setText(taskStatus+ " ASSIGNED TASKS");
    selectedTaskStatus = taskStatus;
    fetchtaskslist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        btnViewDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasklist = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tasklist1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jbbck1 = new javax.swing.JButton();
        btnViewDetails1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tasklist2 = new javax.swing.JTable();

        btnViewDetails.setBackground(new java.awt.Color(0, 0, 153));
        btnViewDetails.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("DETAILS");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        tasklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TITLE", "DESCRIPTION", "EMPLOYEE NAME", "PROJECT NAME"
            }
        ));
        tasklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasklistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tasklist);

        tasklist1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TITLE", "DESCRIPTION", "EMPLOYEE NAME", "PROJECT NAME"
            }
        ));
        tasklist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasklist1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tasklist1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbTitle.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        lbTitle.setText("ASSIGNED TASKS ");

        jbbck1.setBackground(new java.awt.Color(204, 204, 204));
        jbbck1.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jbbck1.setText("BACK");
        jbbck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbck1ActionPerformed(evt);
            }
        });

        btnViewDetails1.setBackground(new java.awt.Color(0, 0, 153));
        btnViewDetails1.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        btnViewDetails1.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails1.setText("DETAILS");
        btnViewDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetails1ActionPerformed(evt);
            }
        });

        tasklist2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TITLE", "DESCRIPTION", "EMPLOYEE NAME", "PROJECT NAME"
            }
        ));
        tasklist2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasklist2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tasklist2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jbbck1)
                .addGap(43, 43, 43)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnViewDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbbck1)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbbck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbck1ActionPerformed
        EmployeeTaskDashboard d1 = new EmployeeTaskDashboard();
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbbck1ActionPerformed

    private void tasklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklistMouseClicked
//        // TODO add your handling code here:
//        selectedId= idsList.get(tasklist.getSelectedRow());

    }//GEN-LAST:event_tasklistMouseClicked

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        if(selectedId!=-1)
        {
            System.err.println("Selcted Id = "+ selectedId);
            AssignedTaskDetails dt= new AssignedTaskDetails(selectedId);
            dt.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnViewDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetails1ActionPerformed
        // TODO add your handling code here:
        if(selectedId!=-1)
        {
            System.err.println("Selcted Id = "+ selectedId);
            updateemployeetasks up= new updateemployeetasks(selectedId );
            up.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnViewDetails1ActionPerformed

    private void tasklist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklist1MouseClicked
        // TODO add your handling code here:
//        selectedId= idsList.get(tasklist.getSelectedRow());

    }//GEN-LAST:event_tasklist1MouseClicked

    private void tasklist2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklist2MouseClicked
        // TODO add your handling code here:
        selectedId= idsList.get(tasklist2.getSelectedRow());

    }//GEN-LAST:event_tasklist2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managetask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managetask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managetask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managetask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managetask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewDetails1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbbck1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tasklist;
    private javax.swing.JTable tasklist1;
    private javax.swing.JTable tasklist2;
    // End of variables declaration//GEN-END:variables

    private void fetchtaskslist() {
        try {
            UserSession session = UserSession.getInstance();
            int emp_id= session.getId();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/tasks_db","root","");
            if(conn==null)
            {
                System.err.println("Connection error");
            }
            else{
                System.out.println("Connection established");
            }
            PreparedStatement pst = conn.prepareStatement("select * from assigned_tasks where emp_id=? && status=?");
            pst.setInt(1, emp_id);
            pst.setString(2, selectedTaskStatus);
            ResultSet rs=  pst.executeQuery();
            tasklist2.setModel(DbUtils.resultSetToTableModel(rs));
            PreparedStatement pst2 = conn.prepareStatement("select * from assigned_tasks where emp_id=?&& status=?");
            pst2.setInt(1, emp_id);
            pst2.setString(2, selectedTaskStatus);
            ResultSet rs2=  pst.executeQuery();
            while(rs2.next()){
                  idsList.add(rs2.getInt("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empolyeelist.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Empolyeelist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
