/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mainproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hiteshi Joshi
 */
public class updateproject extends javax.swing.JFrame {
     int selectedId=-1;
    /**
     * Creates new form updateproject
     */
    public updateproject() {
        initComponents();
    }
 public updateproject(int sId) {
        initComponents();
        selectedId= sId;
        fetchUserData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfDes = new javax.swing.JTextField();
        tfDeadline = new javax.swing.JTextField();
        updateUser = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfname = new javax.swing.JLabel();
        tfdescription = new javax.swing.JLabel();
        Deadline = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfdescription1 = new javax.swing.JTextField();
        tfdeadline1 = new javax.swing.JTextField();
        updateUser1 = new javax.swing.JButton();
        back2 = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 17)); // NOI18N
        jLabel3.setText("DESCRIPTION");

        tfDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDesActionPerformed(evt);
            }
        });

        tfDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDeadlineActionPerformed(evt);
            }
        });

        updateUser.setBackground(new java.awt.Color(51, 0, 153));
        updateUser.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        updateUser.setForeground(new java.awt.Color(255, 255, 255));
        updateUser.setText("UPDATE ");
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });

        back1.setBackground(new java.awt.Color(204, 204, 204));
        back1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        back1.setText("<  BACK");
        back1.setAlignmentY(0.0F);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE PROJECT");

        tfname.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        tfname.setText("NAME:");

        tfdescription.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        tfdescription.setText("DESCRIPTION:");

        Deadline.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Deadline.setText("DEADLINE:");

        tfdescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdescription1ActionPerformed(evt);
            }
        });

        tfdeadline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeadline1ActionPerformed(evt);
            }
        });

        updateUser1.setBackground(new java.awt.Color(51, 0, 153));
        updateUser1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        updateUser1.setForeground(new java.awt.Color(255, 255, 255));
        updateUser1.setText("UPDATE ");
        updateUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUser1ActionPerformed(evt);
            }
        });

        back2.setBackground(new java.awt.Color(204, 204, 204));
        back2.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        back2.setText("<  BACK");
        back2.setAlignmentY(0.0F);
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(back2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(378, 378, 378))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfname1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdescription)
                            .addComponent(Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdescription1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(tfdeadline1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(updateUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfname1)
                    .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdeadline1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(updateUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDesActionPerformed

    private void tfdescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdescription1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdescription1ActionPerformed

    private void tfDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDeadlineActionPerformed

    private void tfdeadline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeadline1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeadline1ActionPerformed

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // creating a connection
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/tasks_db","root","");
            if(conn==null)
            {
                System.err.println("Connection error");
            }
            else{
                System.out.println("Connection established");
            }

            PreparedStatement pst = conn.prepareStatement("update project set project_name= ?, description=?, deadline=? where project_id =?");
            pst.setInt(4, selectedId);
            pst.setString(1, tfname.getText().toString());
            pst.setString(2, tfdescription.getText().toString());
            pst.setString(3, tfDeadline.getText().toString());

            int status= pst.executeUpdate();
            if(status>= 1)
            {
                ProjectList l2 = new ProjectList ();
                l2.setVisible(true);
                this.setVisible(false);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateUserActionPerformed

    private void updateUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUser1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // creating a connection
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/tasks_db","root","");
            if(conn==null)
            {
                System.err.println("Connection error");
            }
            else{
                System.out.println("Connection established");
            }

            PreparedStatement pst = conn.prepareStatement("update project set project_name= ?, description=?, deadline=? where project_id =?");
            pst.setInt(4, selectedId);
            pst.setString(1, tfname1.getText().toString());
            pst.setString(2, tfdescription1.getText().toString());
            pst.setString(3, tfdeadline1.getText().toString());

            int status= pst.executeUpdate();
            if(status>= 1)
            {
                ProjectList l2 = new  ProjectList ();
                l2.setVisible(true);
                this.setVisible(false);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateUser1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        Dashboard1 d1 = new Dashboard1();
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back1ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        ProjectList l1 = new ProjectList();
        l1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateproject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deadline;
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfDeadline;
    private javax.swing.JTextField tfDes;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfdeadline1;
    private javax.swing.JLabel tfdescription;
    private javax.swing.JTextField tfdescription1;
    private javax.swing.JLabel tfname;
    private javax.swing.JTextField tfname1;
    private javax.swing.JButton updateUser;
    private javax.swing.JButton updateUser1;
    // End of variables declaration//GEN-END:variables

    private void fetchUserData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // creating a connection
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/tasks_db","root","");
            if(conn==null)
            {
                System.err.println("Connection error");
            }
            else{
                System.out.println("Connection established");
            }

            PreparedStatement pst = conn.prepareStatement("select * from project where project_id=? ");
            pst.setInt(1, selectedId);
         

            ResultSet rs= pst.executeQuery();
//            if(status>= 1)
//            {
//                UserList list = new UserList ();
//                list.setVisible(true);
//                this.setVisible(false);
//            }
           if(rs.next())
           {
               tfname1.setText(rs.getString("project_name"));
               tfdescription1.setText(rs.getString("description"));
               tfdeadline1.setText(rs.getString("deadline"));

           }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
